jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8081
#  error:             # Servlet Handle Exception
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal #change this to your database url
    password: manager #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create #update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
#  mvc:   # Spring Handle Exception
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false